// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Input.proto

package com.eecs.collab;

public final class InputProto {
  private InputProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface InputActionOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string c = 1;
    /**
     * <code>optional string c = 1;</code>
     */
    boolean hasC();
    /**
     * <code>optional string c = 1;</code>
     */
    String getC();
    /**
     * <code>optional string c = 1;</code>
     */
    com.google.protobuf.ByteString
        getCBytes();

    // optional int32 newLength = 2;
    /**
     * <code>optional int32 newLength = 2;</code>
     */
    boolean hasNewLength();
    /**
     * <code>optional int32 newLength = 2;</code>
     */
    int getNewLength();

    // optional int32 oldLength = 3;
    /**
     * <code>optional int32 oldLength = 3;</code>
     */
    boolean hasOldLength();
    /**
     * <code>optional int32 oldLength = 3;</code>
     */
    int getOldLength();
  }
  /**
   * Protobuf type {@code com.eecs.collab.InputAction}
   */
  public static final class InputAction extends
      com.google.protobuf.GeneratedMessage
      implements InputActionOrBuilder {
    // Use InputAction.newBuilder() to construct.
    private InputAction(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private InputAction(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final InputAction defaultInstance;
    public static InputAction getDefaultInstance() {
      return defaultInstance;
    }

    public InputAction getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private InputAction(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              c_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              newLength_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              oldLength_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.eecs.collab.InputProto.internal_static_com_eecs_collab_InputAction_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.eecs.collab.InputProto.internal_static_com_eecs_collab_InputAction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.eecs.collab.InputProto.InputAction.class, com.eecs.collab.InputProto.InputAction.Builder.class);
    }

    public static com.google.protobuf.Parser<InputAction> PARSER =
        new com.google.protobuf.AbstractParser<InputAction>() {
      public InputAction parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new InputAction(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<InputAction> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string c = 1;
    public static final int C_FIELD_NUMBER = 1;
    private Object c_;
    /**
     * <code>optional string c = 1;</code>
     */
    public boolean hasC() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string c = 1;</code>
     */
    public String getC() {
      Object ref = c_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          c_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string c = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCBytes() {
      Object ref = c_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        c_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 newLength = 2;
    public static final int NEWLENGTH_FIELD_NUMBER = 2;
    private int newLength_;
    /**
     * <code>optional int32 newLength = 2;</code>
     */
    public boolean hasNewLength() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 newLength = 2;</code>
     */
    public int getNewLength() {
      return newLength_;
    }

    // optional int32 oldLength = 3;
    public static final int OLDLENGTH_FIELD_NUMBER = 3;
    private int oldLength_;
    /**
     * <code>optional int32 oldLength = 3;</code>
     */
    public boolean hasOldLength() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 oldLength = 3;</code>
     */
    public int getOldLength() {
      return oldLength_;
    }

    private void initFields() {
      c_ = "";
      newLength_ = 0;
      oldLength_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getCBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, newLength_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, oldLength_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getCBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, newLength_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, oldLength_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.eecs.collab.InputProto.InputAction parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.eecs.collab.InputProto.InputAction parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.eecs.collab.InputProto.InputAction parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.eecs.collab.InputProto.InputAction parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.eecs.collab.InputProto.InputAction parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.eecs.collab.InputProto.InputAction parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.eecs.collab.InputProto.InputAction parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.eecs.collab.InputProto.InputAction parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.eecs.collab.InputProto.InputAction parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.eecs.collab.InputProto.InputAction parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.eecs.collab.InputProto.InputAction prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.eecs.collab.InputAction}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.eecs.collab.InputProto.InputActionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.eecs.collab.InputProto.internal_static_com_eecs_collab_InputAction_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.eecs.collab.InputProto.internal_static_com_eecs_collab_InputAction_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.eecs.collab.InputProto.InputAction.class, com.eecs.collab.InputProto.InputAction.Builder.class);
      }

      // Construct using com.eecs.collab.InputProto.InputAction.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        c_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        newLength_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        oldLength_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.eecs.collab.InputProto.internal_static_com_eecs_collab_InputAction_descriptor;
      }

      public com.eecs.collab.InputProto.InputAction getDefaultInstanceForType() {
        return com.eecs.collab.InputProto.InputAction.getDefaultInstance();
      }

      public com.eecs.collab.InputProto.InputAction build() {
        com.eecs.collab.InputProto.InputAction result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.eecs.collab.InputProto.InputAction buildPartial() {
        com.eecs.collab.InputProto.InputAction result = new com.eecs.collab.InputProto.InputAction(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.c_ = c_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.newLength_ = newLength_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.oldLength_ = oldLength_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.eecs.collab.InputProto.InputAction) {
          return mergeFrom((com.eecs.collab.InputProto.InputAction)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.eecs.collab.InputProto.InputAction other) {
        if (other == com.eecs.collab.InputProto.InputAction.getDefaultInstance()) return this;
        if (other.hasC()) {
          bitField0_ |= 0x00000001;
          c_ = other.c_;
          onChanged();
        }
        if (other.hasNewLength()) {
          setNewLength(other.getNewLength());
        }
        if (other.hasOldLength()) {
          setOldLength(other.getOldLength());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.eecs.collab.InputProto.InputAction parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.eecs.collab.InputProto.InputAction) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string c = 1;
      private Object c_ = "";
      /**
       * <code>optional string c = 1;</code>
       */
      public boolean hasC() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string c = 1;</code>
       */
      public String getC() {
        Object ref = c_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          c_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string c = 1;</code>
       */
      public com.google.protobuf.ByteString
          getCBytes() {
        Object ref = c_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          c_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string c = 1;</code>
       */
      public Builder setC(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        c_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string c = 1;</code>
       */
      public Builder clearC() {
        bitField0_ = (bitField0_ & ~0x00000001);
        c_ = getDefaultInstance().getC();
        onChanged();
        return this;
      }
      /**
       * <code>optional string c = 1;</code>
       */
      public Builder setCBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        c_ = value;
        onChanged();
        return this;
      }

      // optional int32 newLength = 2;
      private int newLength_ ;
      /**
       * <code>optional int32 newLength = 2;</code>
       */
      public boolean hasNewLength() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 newLength = 2;</code>
       */
      public int getNewLength() {
        return newLength_;
      }
      /**
       * <code>optional int32 newLength = 2;</code>
       */
      public Builder setNewLength(int value) {
        bitField0_ |= 0x00000002;
        newLength_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 newLength = 2;</code>
       */
      public Builder clearNewLength() {
        bitField0_ = (bitField0_ & ~0x00000002);
        newLength_ = 0;
        onChanged();
        return this;
      }

      // optional int32 oldLength = 3;
      private int oldLength_ ;
      /**
       * <code>optional int32 oldLength = 3;</code>
       */
      public boolean hasOldLength() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 oldLength = 3;</code>
       */
      public int getOldLength() {
        return oldLength_;
      }
      /**
       * <code>optional int32 oldLength = 3;</code>
       */
      public Builder setOldLength(int value) {
        bitField0_ |= 0x00000004;
        oldLength_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 oldLength = 3;</code>
       */
      public Builder clearOldLength() {
        bitField0_ = (bitField0_ & ~0x00000004);
        oldLength_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.eecs.collab.InputAction)
    }

    static {
      defaultInstance = new InputAction(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.eecs.collab.InputAction)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_eecs_collab_InputAction_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_eecs_collab_InputAction_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\013Input.proto\022\017com.eecs.collab\">\n\013InputA" +
      "ction\022\t\n\001c\030\001 \001(\t\022\021\n\tnewLength\030\002 \001(\005\022\021\n\to" +
      "ldLength\030\003 \001(\005B\035\n\017com.eecs.collabB\nInput" +
      "Proto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_eecs_collab_InputAction_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_eecs_collab_InputAction_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_eecs_collab_InputAction_descriptor,
              new String[] { "C", "NewLength", "OldLength", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
