// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Input.proto

package edu.umich.imlc.collabrify.collabrify_dummy_app;

public final class InputProto {
  private InputProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface InputActionOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional bool undo = 1;
    /**
     * <code>optional bool undo = 1;</code>
     */
    boolean hasUndo();
    /**
     * <code>optional bool undo = 1;</code>
     */
    boolean getUndo();

    // optional bool init = 2;
    /**
     * <code>optional bool init = 2;</code>
     */
    boolean hasInit();
    /**
     * <code>optional bool init = 2;</code>
     */
    boolean getInit();

    // optional string c = 3;
    /**
     * <code>optional string c = 3;</code>
     */
    boolean hasC();
    /**
     * <code>optional string c = 3;</code>
     */
    java.lang.String getC();
    /**
     * <code>optional string c = 3;</code>
     */
    com.google.protobuf.ByteString
        getCBytes();

    // optional int32 newLength = 4;
    /**
     * <code>optional int32 newLength = 4;</code>
     */
    boolean hasNewLength();
    /**
     * <code>optional int32 newLength = 4;</code>
     */
    int getNewLength();

    // optional int32 oldLength = 5;
    /**
     * <code>optional int32 oldLength = 5;</code>
     */
    boolean hasOldLength();
    /**
     * <code>optional int32 oldLength = 5;</code>
     */
    int getOldLength();
  }
  /**
   * Protobuf type {@code edu.umich.imlc.collabrify.collabrify_dummy_app.InputAction}
   */
  public static final class InputAction extends
      com.google.protobuf.GeneratedMessage
      implements InputActionOrBuilder {
    // Use InputAction.newBuilder() to construct.
    private InputAction(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private InputAction(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final InputAction defaultInstance;
    public static InputAction getDefaultInstance() {
      return defaultInstance;
    }

    public InputAction getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private InputAction(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              undo_ = input.readBool();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              init_ = input.readBool();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              c_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              newLength_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              oldLength_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.internal_static_edu_umich_imlc_collabrify_collabrify_dummy_app_InputAction_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.internal_static_edu_umich_imlc_collabrify_collabrify_dummy_app_InputAction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.InputAction.class, edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.InputAction.Builder.class);
    }

    public static com.google.protobuf.Parser<InputAction> PARSER =
        new com.google.protobuf.AbstractParser<InputAction>() {
      public InputAction parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new InputAction(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<InputAction> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional bool undo = 1;
    public static final int UNDO_FIELD_NUMBER = 1;
    private boolean undo_;
    /**
     * <code>optional bool undo = 1;</code>
     */
    public boolean hasUndo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bool undo = 1;</code>
     */
    public boolean getUndo() {
      return undo_;
    }

    // optional bool init = 2;
    public static final int INIT_FIELD_NUMBER = 2;
    private boolean init_;
    /**
     * <code>optional bool init = 2;</code>
     */
    public boolean hasInit() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bool init = 2;</code>
     */
    public boolean getInit() {
      return init_;
    }

    // optional string c = 3;
    public static final int C_FIELD_NUMBER = 3;
    private java.lang.Object c_;
    /**
     * <code>optional string c = 3;</code>
     */
    public boolean hasC() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string c = 3;</code>
     */
    public java.lang.String getC() {
      java.lang.Object ref = c_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          c_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string c = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCBytes() {
      java.lang.Object ref = c_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        c_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 newLength = 4;
    public static final int NEWLENGTH_FIELD_NUMBER = 4;
    private int newLength_;
    /**
     * <code>optional int32 newLength = 4;</code>
     */
    public boolean hasNewLength() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 newLength = 4;</code>
     */
    public int getNewLength() {
      return newLength_;
    }

    // optional int32 oldLength = 5;
    public static final int OLDLENGTH_FIELD_NUMBER = 5;
    private int oldLength_;
    /**
     * <code>optional int32 oldLength = 5;</code>
     */
    public boolean hasOldLength() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 oldLength = 5;</code>
     */
    public int getOldLength() {
      return oldLength_;
    }

    private void initFields() {
      undo_ = false;
      init_ = false;
      c_ = "";
      newLength_ = 0;
      oldLength_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, undo_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, init_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getCBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, newLength_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, oldLength_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, undo_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, init_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getCBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, newLength_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, oldLength_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.InputAction parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.InputAction parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.InputAction parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.InputAction parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.InputAction parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.InputAction parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.InputAction parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.InputAction parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.InputAction parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.InputAction parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.InputAction prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code edu.umich.imlc.collabrify.collabrify_dummy_app.InputAction}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.InputActionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.internal_static_edu_umich_imlc_collabrify_collabrify_dummy_app_InputAction_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.internal_static_edu_umich_imlc_collabrify_collabrify_dummy_app_InputAction_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.InputAction.class, edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.InputAction.Builder.class);
      }

      // Construct using edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.InputAction.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        undo_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        init_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        c_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        newLength_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        oldLength_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.internal_static_edu_umich_imlc_collabrify_collabrify_dummy_app_InputAction_descriptor;
      }

      public edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.InputAction getDefaultInstanceForType() {
        return edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.InputAction.getDefaultInstance();
      }

      public edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.InputAction build() {
        edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.InputAction result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.InputAction buildPartial() {
        edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.InputAction result = new edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.InputAction(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.undo_ = undo_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.init_ = init_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.c_ = c_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.newLength_ = newLength_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.oldLength_ = oldLength_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.InputAction) {
          return mergeFrom((edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.InputAction)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.InputAction other) {
        if (other == edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.InputAction.getDefaultInstance()) return this;
        if (other.hasUndo()) {
          setUndo(other.getUndo());
        }
        if (other.hasInit()) {
          setInit(other.getInit());
        }
        if (other.hasC()) {
          bitField0_ |= 0x00000004;
          c_ = other.c_;
          onChanged();
        }
        if (other.hasNewLength()) {
          setNewLength(other.getNewLength());
        }
        if (other.hasOldLength()) {
          setOldLength(other.getOldLength());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.InputAction parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.InputAction) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional bool undo = 1;
      private boolean undo_ ;
      /**
       * <code>optional bool undo = 1;</code>
       */
      public boolean hasUndo() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bool undo = 1;</code>
       */
      public boolean getUndo() {
        return undo_;
      }
      /**
       * <code>optional bool undo = 1;</code>
       */
      public Builder setUndo(boolean value) {
        bitField0_ |= 0x00000001;
        undo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool undo = 1;</code>
       */
      public Builder clearUndo() {
        bitField0_ = (bitField0_ & ~0x00000001);
        undo_ = false;
        onChanged();
        return this;
      }

      // optional bool init = 2;
      private boolean init_ ;
      /**
       * <code>optional bool init = 2;</code>
       */
      public boolean hasInit() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bool init = 2;</code>
       */
      public boolean getInit() {
        return init_;
      }
      /**
       * <code>optional bool init = 2;</code>
       */
      public Builder setInit(boolean value) {
        bitField0_ |= 0x00000002;
        init_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool init = 2;</code>
       */
      public Builder clearInit() {
        bitField0_ = (bitField0_ & ~0x00000002);
        init_ = false;
        onChanged();
        return this;
      }

      // optional string c = 3;
      private java.lang.Object c_ = "";
      /**
       * <code>optional string c = 3;</code>
       */
      public boolean hasC() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string c = 3;</code>
       */
      public java.lang.String getC() {
        java.lang.Object ref = c_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          c_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string c = 3;</code>
       */
      public com.google.protobuf.ByteString
          getCBytes() {
        java.lang.Object ref = c_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          c_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string c = 3;</code>
       */
      public Builder setC(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        c_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string c = 3;</code>
       */
      public Builder clearC() {
        bitField0_ = (bitField0_ & ~0x00000004);
        c_ = getDefaultInstance().getC();
        onChanged();
        return this;
      }
      /**
       * <code>optional string c = 3;</code>
       */
      public Builder setCBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        c_ = value;
        onChanged();
        return this;
      }

      // optional int32 newLength = 4;
      private int newLength_ ;
      /**
       * <code>optional int32 newLength = 4;</code>
       */
      public boolean hasNewLength() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 newLength = 4;</code>
       */
      public int getNewLength() {
        return newLength_;
      }
      /**
       * <code>optional int32 newLength = 4;</code>
       */
      public Builder setNewLength(int value) {
        bitField0_ |= 0x00000008;
        newLength_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 newLength = 4;</code>
       */
      public Builder clearNewLength() {
        bitField0_ = (bitField0_ & ~0x00000008);
        newLength_ = 0;
        onChanged();
        return this;
      }

      // optional int32 oldLength = 5;
      private int oldLength_ ;
      /**
       * <code>optional int32 oldLength = 5;</code>
       */
      public boolean hasOldLength() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 oldLength = 5;</code>
       */
      public int getOldLength() {
        return oldLength_;
      }
      /**
       * <code>optional int32 oldLength = 5;</code>
       */
      public Builder setOldLength(int value) {
        bitField0_ |= 0x00000010;
        oldLength_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 oldLength = 5;</code>
       */
      public Builder clearOldLength() {
        bitField0_ = (bitField0_ & ~0x00000010);
        oldLength_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:edu.umich.imlc.collabrify.collabrify_dummy_app.InputAction)
    }

    static {
      defaultInstance = new InputAction(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:edu.umich.imlc.collabrify.collabrify_dummy_app.InputAction)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_umich_imlc_collabrify_collabrify_dummy_app_InputAction_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_edu_umich_imlc_collabrify_collabrify_dummy_app_InputAction_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Input.proto\022.edu.umich.imlc.collabrify" +
      ".collabrify_dummy_app\"Z\n\013InputAction\022\014\n\004" +
      "undo\030\001 \001(\010\022\014\n\004init\030\002 \001(\010\022\t\n\001c\030\003 \001(\t\022\021\n\tn" +
      "ewLength\030\004 \001(\005\022\021\n\toldLength\030\005 \001(\005B<\n.edu" +
      ".umich.imlc.collabrify.collabrify_dummy_" +
      "appB\nInputProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_edu_umich_imlc_collabrify_collabrify_dummy_app_InputAction_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_edu_umich_imlc_collabrify_collabrify_dummy_app_InputAction_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_edu_umich_imlc_collabrify_collabrify_dummy_app_InputAction_descriptor,
              new java.lang.String[] { "Undo", "Init", "C", "NewLength", "OldLength", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
