// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Input.proto

package edu.umich.imlc.collabrify.collabrify_dummy_app;

public final class InputProto {
  private InputProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface InputActionOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional bool isInsert = 1;
    /**
     * <code>optional bool isInsert = 1;</code>
     */
    boolean hasIsInsert();
    /**
     * <code>optional bool isInsert = 1;</code>
     */
    boolean getIsInsert();

    // optional string c = 3;
    /**
     * <code>optional string c = 3;</code>
     */
    boolean hasC();
    /**
     * <code>optional string c = 3;</code>
     */
    java.lang.String getC();
    /**
     * <code>optional string c = 3;</code>
     */
    com.google.protobuf.ByteString
        getCBytes();

    // optional int32 uid = 6;
    /**
     * <code>optional int32 uid = 6;</code>
     */
    boolean hasUid();
    /**
     * <code>optional int32 uid = 6;</code>
     */
    int getUid();

    // optional int32 index = 7;
    /**
     * <code>optional int32 index = 7;</code>
     */
    boolean hasIndex();
    /**
     * <code>optional int32 index = 7;</code>
     */
    int getIndex();
  }
  /**
   * Protobuf type {@code edu.umich.imlc.collabrify.collabrify_dummy_app.InputAction}
   */
  public static final class InputAction extends
      com.google.protobuf.GeneratedMessage
      implements InputActionOrBuilder {
    // Use InputAction.newBuilder() to construct.
    private InputAction(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private InputAction(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final InputAction defaultInstance;
    public static InputAction getDefaultInstance() {
      return defaultInstance;
    }

    public InputAction getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private InputAction(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              isInsert_ = input.readBool();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000002;
              c_ = input.readBytes();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000004;
              uid_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000008;
              index_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.internal_static_edu_umich_imlc_collabrify_collabrify_dummy_app_InputAction_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.internal_static_edu_umich_imlc_collabrify_collabrify_dummy_app_InputAction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.InputAction.class, edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.InputAction.Builder.class);
    }

    public static com.google.protobuf.Parser<InputAction> PARSER =
        new com.google.protobuf.AbstractParser<InputAction>() {
      public InputAction parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new InputAction(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<InputAction> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional bool isInsert = 1;
    public static final int ISINSERT_FIELD_NUMBER = 1;
    private boolean isInsert_;
    /**
     * <code>optional bool isInsert = 1;</code>
     */
    public boolean hasIsInsert() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bool isInsert = 1;</code>
     */
    public boolean getIsInsert() {
      return isInsert_;
    }

    // optional string c = 3;
    public static final int C_FIELD_NUMBER = 3;
    private java.lang.Object c_;
    /**
     * <code>optional string c = 3;</code>
     */
    public boolean hasC() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string c = 3;</code>
     */
    public java.lang.String getC() {
      java.lang.Object ref = c_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          c_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string c = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCBytes() {
      java.lang.Object ref = c_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        c_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 uid = 6;
    public static final int UID_FIELD_NUMBER = 6;
    private int uid_;
    /**
     * <code>optional int32 uid = 6;</code>
     */
    public boolean hasUid() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 uid = 6;</code>
     */
    public int getUid() {
      return uid_;
    }

    // optional int32 index = 7;
    public static final int INDEX_FIELD_NUMBER = 7;
    private int index_;
    /**
     * <code>optional int32 index = 7;</code>
     */
    public boolean hasIndex() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 index = 7;</code>
     */
    public int getIndex() {
      return index_;
    }

    private void initFields() {
      isInsert_ = false;
      c_ = "";
      uid_ = 0;
      index_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, isInsert_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(3, getCBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(6, uid_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(7, index_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, isInsert_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getCBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, uid_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, index_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.InputAction parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.InputAction parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.InputAction parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.InputAction parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.InputAction parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.InputAction parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.InputAction parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.InputAction parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.InputAction parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.InputAction parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.InputAction prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code edu.umich.imlc.collabrify.collabrify_dummy_app.InputAction}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.InputActionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.internal_static_edu_umich_imlc_collabrify_collabrify_dummy_app_InputAction_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.internal_static_edu_umich_imlc_collabrify_collabrify_dummy_app_InputAction_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.InputAction.class, edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.InputAction.Builder.class);
      }

      // Construct using edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.InputAction.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        isInsert_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        c_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        uid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        index_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.internal_static_edu_umich_imlc_collabrify_collabrify_dummy_app_InputAction_descriptor;
      }

      public edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.InputAction getDefaultInstanceForType() {
        return edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.InputAction.getDefaultInstance();
      }

      public edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.InputAction build() {
        edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.InputAction result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.InputAction buildPartial() {
        edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.InputAction result = new edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.InputAction(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.isInsert_ = isInsert_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.c_ = c_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.uid_ = uid_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.index_ = index_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.InputAction) {
          return mergeFrom((edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.InputAction)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.InputAction other) {
        if (other == edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.InputAction.getDefaultInstance()) return this;
        if (other.hasIsInsert()) {
          setIsInsert(other.getIsInsert());
        }
        if (other.hasC()) {
          bitField0_ |= 0x00000002;
          c_ = other.c_;
          onChanged();
        }
        if (other.hasUid()) {
          setUid(other.getUid());
        }
        if (other.hasIndex()) {
          setIndex(other.getIndex());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.InputAction parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.umich.imlc.collabrify.collabrify_dummy_app.InputProto.InputAction) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional bool isInsert = 1;
      private boolean isInsert_ ;
      /**
       * <code>optional bool isInsert = 1;</code>
       */
      public boolean hasIsInsert() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bool isInsert = 1;</code>
       */
      public boolean getIsInsert() {
        return isInsert_;
      }
      /**
       * <code>optional bool isInsert = 1;</code>
       */
      public Builder setIsInsert(boolean value) {
        bitField0_ |= 0x00000001;
        isInsert_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool isInsert = 1;</code>
       */
      public Builder clearIsInsert() {
        bitField0_ = (bitField0_ & ~0x00000001);
        isInsert_ = false;
        onChanged();
        return this;
      }

      // optional string c = 3;
      private java.lang.Object c_ = "";
      /**
       * <code>optional string c = 3;</code>
       */
      public boolean hasC() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string c = 3;</code>
       */
      public java.lang.String getC() {
        java.lang.Object ref = c_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          c_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string c = 3;</code>
       */
      public com.google.protobuf.ByteString
          getCBytes() {
        java.lang.Object ref = c_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          c_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string c = 3;</code>
       */
      public Builder setC(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        c_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string c = 3;</code>
       */
      public Builder clearC() {
        bitField0_ = (bitField0_ & ~0x00000002);
        c_ = getDefaultInstance().getC();
        onChanged();
        return this;
      }
      /**
       * <code>optional string c = 3;</code>
       */
      public Builder setCBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        c_ = value;
        onChanged();
        return this;
      }

      // optional int32 uid = 6;
      private int uid_ ;
      /**
       * <code>optional int32 uid = 6;</code>
       */
      public boolean hasUid() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 uid = 6;</code>
       */
      public int getUid() {
        return uid_;
      }
      /**
       * <code>optional int32 uid = 6;</code>
       */
      public Builder setUid(int value) {
        bitField0_ |= 0x00000004;
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 uid = 6;</code>
       */
      public Builder clearUid() {
        bitField0_ = (bitField0_ & ~0x00000004);
        uid_ = 0;
        onChanged();
        return this;
      }

      // optional int32 index = 7;
      private int index_ ;
      /**
       * <code>optional int32 index = 7;</code>
       */
      public boolean hasIndex() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 index = 7;</code>
       */
      public int getIndex() {
        return index_;
      }
      /**
       * <code>optional int32 index = 7;</code>
       */
      public Builder setIndex(int value) {
        bitField0_ |= 0x00000008;
        index_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 index = 7;</code>
       */
      public Builder clearIndex() {
        bitField0_ = (bitField0_ & ~0x00000008);
        index_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:edu.umich.imlc.collabrify.collabrify_dummy_app.InputAction)
    }

    static {
      defaultInstance = new InputAction(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:edu.umich.imlc.collabrify.collabrify_dummy_app.InputAction)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_umich_imlc_collabrify_collabrify_dummy_app_InputAction_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_edu_umich_imlc_collabrify_collabrify_dummy_app_InputAction_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Input.proto\022.edu.umich.imlc.collabrify" +
      ".collabrify_dummy_app\"F\n\013InputAction\022\020\n\010" +
      "isInsert\030\001 \001(\010\022\t\n\001c\030\003 \001(\t\022\013\n\003uid\030\006 \001(\005\022\r" +
      "\n\005index\030\007 \001(\005B<\n.edu.umich.imlc.collabri" +
      "fy.collabrify_dummy_appB\nInputProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_edu_umich_imlc_collabrify_collabrify_dummy_app_InputAction_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_edu_umich_imlc_collabrify_collabrify_dummy_app_InputAction_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_edu_umich_imlc_collabrify_collabrify_dummy_app_InputAction_descriptor,
              new java.lang.String[] { "IsInsert", "C", "Uid", "Index", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
